spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    database: ${SPRING_JPA_DATABASE}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TRUST}
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
          connectiontimeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT}
          timeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}
          writetimeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT}

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}

springdoc:
  default-produces-media-type: ${SPRINGDOC_DEFAULT_PRODUCES_MEDIA_TYPE}

server:
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: ${APPLICATION_SECURITY_JWT_EXPIRATION}
  mailing:
    frontend:
      activation-url: ${APPLICATION_MAILING_FRONTEND_ACTIVATION_URL}
